channels:
- conda-forge
- defaults
dependencies:
- python=3.10
- mamba
- jupyterlab
- sphinx
- sphinx-book-theme
- sphinxcontrib-bibtex
- sphinx-copybutton
- sphinx-design
- sphinx-favicon
- myst-nb
- numpy
- matplotlib

